### ISSUE TITLE
Configuring the JSON sent to loggly

### ISSUE THREAD

**Issue by roytz** [loggly/winston-loggly-bulk#15]
Hi,
I use winston with this package but I want to configure the JSON being sent to loggly.
How can I do that?

**Comment by mostlyjason** [comment]
What do you mean by configure the JSON? Do you want to modify the JSON being sent to Loggly? In what way?

**Comment by shai32** [comment]
@mostlyjason
Adding more fields like:
App-name 
Path (where the log from, which file which line)
and other fields that will help me filter logs letter in loggly

**Comment by mostlyjason** [comment]
I believe winston allows you to add metadata to your log messages like this: https://github.com/winstonjs/winston#logging-with-metadata. Does this satisfy your need or do you have another suggestion?

**Comment by roytz** [comment]
Hi @mostlyjason ,
Thank you! That was what we were looking for.
btw, lots of times I see not all of my logs are transferred to loggly (but some do), any idea why?

**Comment by mostlyjason** [comment]
@roytz that sounds like a separate issue. Can you open a support ticket so we can help you with that? https://community.loggly.com/customer/portal/emails/new

**Comment by mostlyjason** [comment]
Looks like we addressed this issue so I'm closing it. Please reopen if needed.
