### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by richkn** [loggly/winston-loggly-bulk#17]
nsp check reports two vulnerabilities:

1. ReDoS via long string of semicolons - https://nodesecurity.io/advisories/130
2. Remote Memory Exposure - https://nodesecurity.io/advisories/309

These advisories recommend package upgrades for:
_request_ to 2.68.0 or higher 
_tough-cookie_ to 2.3.0

**Comment by mostlyjason** [comment]
Thanks we will work on getting these updated

**Comment by mostlyjason** [comment]
This has been addressed, closing
