### ISSUE TITLE
TypeError: winston.transports.Loggly is not a constructor

### ISSUE THREAD

**Issue by jimdubbs** [loggly/winston-loggly-bulk#27]
Hey Guys,

Running into an odd problem here. using the package everything builds/tests locally fine - but my TravisCI is failing with the "TypeError: winston.transports.Loggly is not a constructor". I seen a 1 other issue about this referencing node version/module mismatch. I've confirmed im using the same version of node both locally and in TravisCI. any thoughts?

```
"winston": "2.3.1",
 "winston-loggly-bulk": "2.0.1"
```

**Comment by mostlyjason** [comment]
This sounds like the error we saw in #26

**Comment by mostlyjason** [comment]
Closing this one as a duplicate
