### ISSUE TITLE
Error message lost during logging

### ISSUE THREAD

**Issue by lionello** [loggly/winston-loggly-bulk#29]
This line https://github.com/loggly/winston-loggly-bulk/blob/master/lib/winston-loggly.js#L122 overwrites any field `message` in the meta object. When meta is an `instanceof Error`, this effectively replaces the error message from the object with an empty string.

A quick fix could be to do 
```javascript
  message.message = msg || message.message;
```

**Comment by mostlyjason** [comment]
Thanks for reporting this! We will have one of our engineers take a look

**Comment by Shwetajain148** [comment]
Hi @lionello, Since this issue has been handled in the **winston-loggly-bulk's** 2.0.2 release, I am going ahead and closing this one.
