### ISSUE TITLE
Can not tag an error when passed to `.error` or `.info` function.

### ISSUE THREAD

**Issue by shahidcodes** [loggly/winston-loggly-bulk#44]
Error tags works when tags are passing when instantiating the transport
```javascript
const options = {
  token: "85dc8260-d031-49be-a3a2-d48e47f97125",
  subdomain: "sub",
  tags: ['test tags']
  json: true
}
```
but not when when passed to `.error` or `.info` function.
```javascript
Loggly.error(err, { tags: ['user_login'] })
// or
Loggly.error(err, ['user_login']);
```

I can see the code passes the tags array to underlying `node-loggly-bulk` but why it does'nt appear as tag in Loggly rather its appended in `json` as an extra property called `meta`

versions from package.json
```javascript
{
"winston": "^2.4.1",
"winston-loggly-bulk": "^2.0.2",
}
```

**Comment by elfilip** [comment]
I tested it on 3.x branch and it works. When I call:
`logger.info("Hello World from Node.js! ",{ tags: ['user_login'] });`
The tag shows in the list of tags in Loggly.
