### ISSUE TITLE
Vulnerability due to usage of lodash.clonedeep:4.5.0

### ISSUE THREAD

**Issue by Mohammad-sabbagh** [loggly/winston-loggly-bulk#67]
lodash node module before 4.17.5 suffers from a Modification of Assumed-Immutable Data (MAID) vulnerability via defaultsDeep, merge, and mergeWith functions, which allows a malicious user to modify the prototype of "Object" via __proto__, causing the addition or modification of an existing property that will exist on all objects.

details https://ossindex.sonatype.org/vuln/12e63c9c-b3f9-42d3-8541-dca1b72cad69

**Comment by michaljanda** [comment]
Thank you for the report. The dependency should be updated now. Feel free to reopen it if you find it unresolved.
