### ISSUE TITLE
Is the library maintenance stoped?

### ISSUE THREAD

**Issue by adarshmadrecha** [loggly/winston-loggly-bulk#92]
There are multiple vulnerabilities reported by various issues. 

- [x] #90 
- [x] #89 
- [x] #88 
- [x] #86 
- [x] #85 
- [x] #83 
- [x] #82 
- [x] #81
- [x] #80
- [x] #68 

Dear Maintainer/s,
Are you planning to update the packages to fix these vulnerabilities?
Are you looking for new maintainers?
Are you accepting PRs for these fixes?

**Comment by adarshmadrecha** [comment]
The idea of this issue is to offer help. The library is fairly popular (see downloads below).
I genuinely believe that if the library is well maintained, it will lead to more users choosing loggly service over other providers.
Hence, maintaining the liabaray makes commercial sense.

![image](https://github.com/loggly/winston-loggly-bulk/assets/11911938/cdeec34f-ae26-45d4-ba24-3bb065c3bf3e)
Ref: https://npm-stat.com/charts.html?package=winston-loggly-bulk&from=2022-06-01&to=2023-07-30

In the mean time, I have started forked the repo and started making changes to ensure `npm audit` does not show any vulnerabilities. I also noted that in order to fix all the vulnerabilities, will also need to make changes to the dependent package `node-loggly-bulk`.
1. https://github.com/adarshmadrecha/node-loggly-bulk
2. https://github.com/adarshmadrecha/winston-loggly-bulk

I am still trying to ensure that all tests pass in both the libraries. If you are accepting PRs, would love to fix these issues.

**Comment by adarshmadrecha** [comment]
@danriti @snorecone @michaljanda 
Sorry for pinging, but wanted to bring this issue to your attention.

**Comment by zdenek-machek-swi** [comment]
New version 3.3.0 with updated packages was published
